/**
 * Canonical auth fixtures for ZeroU-emitted vitest tests (Phase 11.3).
 *
 * These are TEMPLATES — strings that get written to
 * `<cwd>/tests/__zerou__/fixtures/auth-<kind>.ts` once per audit run.
 * Vitest tests then `import { mockAuthenticatedUser, mockAnonymous } from
 * '../fixtures/auth-<kind>'` and call those helpers inside `beforeEach`.
 *
 * IMPORTANT: this file is NOT auto-loaded. Loading it as a module must NOT
 * trigger any `vi.mock(...)` side effect at fixture-file load time. The
 * generated fixture file uses `vi.mock(...)` at its top because vitest
 * hoists it — but this `auth-fixtures.ts` source file only exposes the
 * templates as plain strings.
 *
 * Per-kind fixture API contract (consumers can rely on these exports):
 *   - `mockAuthenticatedUser(user?)` — mocks the auth helper to return a user.
 *   - `mockAnonymous()` — mocks the auth helper to return null/empty.
 *   - `resetAuth()` — restores the mock to the anonymous default.
 */
import type { AuthKind } from './auth-detector.js';

/** Supabase-SSR canonical fixture. Mocks `getServerUser` from `@/lib/auth/server`. */
export const SUPABASE_SSR_FIXTURE = `// ZEROU AUTOGENERATED — canonical Supabase-SSR auth fixture.
// Vitest tests import \`mockAuthenticatedUser / mockAnonymous / resetAuth\`
// from this module and call them inside beforeEach.
//
// NOTE: the import path "@/lib/auth/server" is the most common location for
// Supabase-SSR auth helpers in Next.js projects. If your helper lives elsewhere
// (e.g. \`lib/supabase/server\`, \`src/auth\`), adjust the vi.mock(...) target
// below to point at the right module specifier.
import { vi } from 'vitest';

interface MockUser {
  id: string;
  email: string;
}

const mockState: { user: MockUser | null } = { user: null };

vi.mock('@/lib/auth/server', () => ({
  getServerUser: () => Promise.resolve(mockState.user),
  getServerUserOrThrow: () => {
    if (!mockState.user) throw new Error('Unauthorized');
    return Promise.resolve(mockState.user);
  },
  createSupabaseServerClient: () => Promise.resolve({
    auth: {
      getUser: () => Promise.resolve({ data: { user: mockState.user }, error: null }),
    },
  }),
}));

export function mockAuthenticatedUser(user: MockUser = { id: 'test-user-1', email: 'test@example.com' }): void {
  mockState.user = user;
}

export function mockAnonymous(): void {
  mockState.user = null;
}

export function resetAuth(): void {
  mockState.user = null;
}
`;

/** NextAuth canonical fixture. Mocks `getServerSession` from `next-auth`. */
export const NEXTAUTH_FIXTURE = `// ZEROU AUTOGENERATED — canonical NextAuth auth fixture.
// Vitest tests import \`mockAuthenticatedUser / mockAnonymous / resetAuth\`
// from this module and call them inside beforeEach.
//
// NOTE: this fixture mocks both \`next-auth\` (getServerSession) and the
// app's local \`auth\` helper if you re-export it from \`@/auth\` or
// \`@/lib/auth\`. Adjust the vi.mock(...) targets if your project uses a
// different specifier.
import { vi } from 'vitest';

interface MockUser {
  id: string;
  email: string;
}

interface MockSession {
  user: MockUser;
  expires?: string;
}

const mockState: { session: MockSession | null } = { session: null };

vi.mock('next-auth', () => ({
  getServerSession: () => Promise.resolve(mockState.session),
  default: () => Promise.resolve(mockState.session),
}));

vi.mock('@/auth', () => ({
  auth: () => Promise.resolve(mockState.session),
}));

vi.mock('@/lib/auth', () => ({
  auth: () => Promise.resolve(mockState.session),
  getServerSession: () => Promise.resolve(mockState.session),
}));

export function mockAuthenticatedUser(
  session: MockSession = { user: { id: 'test-user-1', email: 'test@example.com' } },
): void {
  mockState.session = session;
}

export function mockAnonymous(): void {
  mockState.session = null;
}

export function resetAuth(): void {
  mockState.session = null;
}
`;

/** Return the fixture template string for a given auth kind. */
export function fixtureFor(kind: AuthKind): string | null {
  switch (kind) {
    case 'supabase-ssr':
      return SUPABASE_SSR_FIXTURE;
    case 'nextauth':
      return NEXTAUTH_FIXTURE;
    default:
      return null;
  }
}

/** Stable relative path (from emitter outDir) of the fixture file for a kind. */
export function fixtureRelImport(kind: AuthKind): string {
  // Emitter writes fixtures to <outDir>/fixtures/auth-<kind>.ts and test
  // files live in <outDir>. So tests import `./fixtures/auth-<kind>`.
  return `./fixtures/auth-${kind}`;
}

/** File-on-disk name (under <outDir>/fixtures/). */
export function fixtureFileName(kind: AuthKind): string {
  return `auth-${kind}.ts`;
}
