/**
 * Test emitter (Phase 8 Track 8B).
 *
 * Converts `TestCaseSpec[]` (produced by `test-case-generator.ts`) into real
 * Vitest `.test.ts` files written under `<cwd>/tests/__zerou__/`. When a
 * critic LLM is configured the body of each test is generated by the LLM
 * (mock setup + assertions). When no critic is configured we fall back to
 * `it.todo(...)` so vitest still parses the file but treats the case as
 * pending (no false failures, no false passes).
 *
 * Surface authority:
 *   `docs/plans/2026-05-26-phase-8-real-tests-progressive-report.md`
 *   §"agent/test-emitter.ts (Track 8B)".
 *
 * Events emitted (see plan §"Decision-Branch Log Taxonomy"):
 *   agent.emit.start
 *   agent.emit.file.start
 *   agent.emit.spec.llm-call.start
 *   agent.emit.spec.llm-call.success
 *   agent.emit.spec.llm-call.failure
 *   agent.emit.spec.fallback-todo
 *   agent.emit.file.written
 *   agent.emit.complete
 */
import * as fs from 'node:fs';
import path from 'node:path';
import type { TrackLogger } from '../log-types.js';
import { logBranch, logCatch } from '../log/branch.js';
import type { EngineConfig } from '../stubs.js';
import type { TestCaseSpec } from './types.js';
import type { FunctionInfo } from './ast-types-stub.js';

// ── Public surface ──────────────────────────────────────────────────────────

export interface EmittedTestFile {
  /** Absolute path to the written `.test.ts` file. */
  path: string;
  /** Number of `it(...)` / `it.todo(...)` cases in this file. */
  testCount: number;
  /** TestCaseSpec.id values that landed in this file. */
  specsCovered: string[];
  /** Source LOC of the emitted file (newline count). */
  sourceLOC: number;
}

export interface EmitOptions {
  specs: TestCaseSpec[];
  functions: FunctionInfo[];
  cwd: string;
  /** Default `<cwd>/tests/__zerou__`. */
  outDir?: string;
  logger: TrackLogger;
  criticConfig?: EngineConfig | null;
  criticApiKey?: string | null;
  /** Injectable LLM caller — used by tests to avoid hitting a real provider. */
  callLLM?: EmitLlmCaller;
  /** Per-spec LLM call timeout. Default 30s. */
  timeoutMs?: number;
}

/**
 * LLM call hook used to fill in test body + imports. Mirrors the pattern in
 * `test-spec-runner.ts`. The returned `rawText` is expected to contain JSON
 * with `imports` and `body` string fields (see `parseLlmBody` below).
 */
export type EmitLlmCaller = (args: {
  systemPrompt: string;
  userPrompt: string;
  criticConfig: EngineConfig;
  apiKey: string;
  timeoutMs: number;
}) => Promise<{ rawText: string; durationMs: number }>;

/** Public entry point. Writes one `.test.ts` file per source file targeted. */
export async function emitVitestTests(opts: EmitOptions): Promise<EmittedTestFile[]> {
  const start = Date.now();
  const { logger } = opts;
  const outDir = opts.outDir ?? path.join(opts.cwd, 'tests', '__zerou__');
  const timeoutMs = opts.timeoutMs ?? DEFAULT_TIMEOUT_MS;
  const hasLlm = !!(opts.criticConfig && opts.criticApiKey);

  logger.log('info', 'agent.emit.start', {
    specCount: opts.specs.length,
    functionCount: opts.functions.length,
    outDir,
    hasLlm,
  });

  // Bucket specs by spec.scope.file → one .test.ts per source file.
  const buckets = bucketByTarget(opts.specs);
  const files: EmittedTestFile[] = [];

  // Ensure the output directory exists (idempotent).
  fs.mkdirSync(outDir, { recursive: true });

  for (const [targetFile, specs] of buckets) {
    logger.log('info', 'agent.emit.file.start', {
      targetFile,
      specCount: specs.length,
    });

    const fnByKey = indexFunctions(opts.functions);
    const rendered: RenderedSpec[] = [];
    const collectedImports = new Set<string>();
    collectedImports.add(`import { describe, it, expect, vi } from 'vitest';`);

    for (const spec of specs) {
      const fnInfo = pickFunctionInfo(spec, fnByKey);
      const r = await renderSpec({
        spec,
        fnInfo,
        targetFile,
        outDir,
        cwd: opts.cwd,
        logger,
        criticConfig: opts.criticConfig ?? null,
        criticApiKey: opts.criticApiKey ?? null,
        callLLM: opts.callLLM,
        timeoutMs,
      });
      rendered.push(r);
      for (const imp of r.imports) collectedImports.add(imp);
    }

    const outFilePath = path.join(outDir, `${slugifyTarget(targetFile)}.test.ts`);
    const content = buildFileContent({
      targetFile,
      imports: [...collectedImports],
      rendered,
    });

    try {
      fs.writeFileSync(outFilePath, content, 'utf8');
    } catch (e) {
      logCatch(logger, 'agent.emit.file.write-decision', e, {
        path: outFilePath,
      });
      throw e;
    }

    const sourceLOC = content.split(/\r?\n/).length;
    logger.log('info', 'agent.emit.file.written', {
      path: outFilePath,
      testCount: rendered.length,
      bytes: Buffer.byteLength(content, 'utf8'),
      sourceLOC,
    });

    files.push({
      path: outFilePath,
      testCount: rendered.length,
      specsCovered: rendered.map((r) => r.spec.id),
      sourceLOC,
    });
  }

  logger.log('info', 'agent.emit.complete', {
    fileCount: files.length,
    totalTests: files.reduce((n, f) => n + f.testCount, 0),
    durationMs: Date.now() - start,
  });

  return files;
}

// ── Internals ───────────────────────────────────────────────────────────────

const DEFAULT_TIMEOUT_MS = 30_000;

const SYSTEM_PROMPT = [
  'You are a senior TypeScript test engineer. You write Vitest tests that run in',
  'Node. Given one test specification and the source code under test, output the',
  'body of a single `it(...)` block plus any needed imports.',
  '',
  'OUTPUT FORMAT: strict JSON only, no markdown fence, no preamble. Schema:',
  '{',
  '  "imports": "string — newline-separated extra import statements (may be empty)",',
  '  "body":    "string — the JavaScript/TypeScript inside the it() callback"',
  '}',
  '',
  'Rules:',
  ' - Do NOT include `it(...)`, `describe(...)`, `import { it } from vitest` —',
  '   the harness already provides those.',
  ' - Prefer `await import("<relative path>")` over top-level import for the',
  '   target module so dynamic loading errors do not break collection.',
  ' - Use `vi.mock()` for db / network calls when the source code uses them.',
  ' - Keep the body under 60 lines. If you cannot write a meaningful test,',
  '   return `{"imports": "", "body": "expect.fail(\'TODO: unable to author\');"}`.',
].join('\n');

interface RenderedSpec {
  spec: TestCaseSpec;
  imports: string[];                // extra imports to merge at file top
  body: string;                     // the body of `it(...)`
  isTodo: boolean;                  // true if fell back to it.todo(...)
}

interface RenderSpecArgs {
  spec: TestCaseSpec;
  fnInfo: FunctionInfo | null;
  targetFile: string;               // POSIX-relative source file
  outDir: string;
  cwd: string;
  logger: TrackLogger;
  criticConfig: EngineConfig | null;
  criticApiKey: string | null;
  callLLM?: EmitLlmCaller;
  timeoutMs: number;
}

async function renderSpec(args: RenderSpecArgs): Promise<RenderedSpec> {
  const { spec, fnInfo, targetFile, outDir, cwd, logger } = args;

  if (!args.criticConfig || !args.criticApiKey) {
    logBranch(logger, 'agent.emit.spec.fallback-todo', {
      decision: 'no-llm-key',
      specId: spec.id,
      reason: 'no critic config or api key',
    });
    return {
      spec,
      imports: [],
      body: `it.todo(${JSON.stringify(spec.name)});`,
      isTodo: true,
    };
  }

  const relImportPath = computeRelativeImport(outDir, targetFile, cwd);
  const userPrompt = buildEmitUserPrompt({
    spec,
    fnInfo,
    relImportPath,
  });

  logger.log('info', 'agent.emit.spec.llm-call.start', {
    specId: spec.id,
    model: args.criticConfig.modelId,
    promptLen: userPrompt.length,
  });

  let rawText = '';
  const callStart = Date.now();
  try {
    const caller = args.callLLM ?? defaultEmitLlmCaller;
    const out = await caller({
      systemPrompt: SYSTEM_PROMPT,
      userPrompt,
      criticConfig: args.criticConfig,
      apiKey: args.criticApiKey,
      timeoutMs: args.timeoutMs,
    });
    rawText = out.rawText;
    logger.log('info', 'agent.emit.spec.llm-call.success', {
      specId: spec.id,
      durationMs: out.durationMs,
      rawLen: rawText.length,
    });
  } catch (e) {
    const msg = e instanceof Error ? e.message : String(e);
    logger.log('warn', 'agent.emit.spec.llm-call.failure', {
      specId: spec.id,
      error: msg.slice(0, 300),
      durationMs: Date.now() - callStart,
    });
    logBranch(logger, 'agent.emit.spec.fallback-todo', {
      decision: 'llm-failure',
      specId: spec.id,
      reason: 'llm call threw',
    });
    return {
      spec,
      imports: [],
      body: `it.todo(${JSON.stringify(spec.name)});`,
      isTodo: true,
    };
  }

  const parsed = parseLlmBody(rawText, logger, spec.id);
  if (!parsed.ok) {
    logBranch(logger, 'agent.emit.spec.fallback-todo', {
      decision: 'parse-failure',
      specId: spec.id,
      reason: parsed.error,
    });
    return {
      spec,
      imports: [],
      body: `it.todo(${JSON.stringify(spec.name)});`,
      isTodo: true,
    };
  }

  const importLines = parsed.imports
    .split(/\r?\n/)
    .map((s) => s.trim())
    .filter((s) => s.length > 0);

  return {
    spec,
    imports: importLines,
    body: wrapWithGwtComment(spec, parsed.body),
    isTodo: false,
  };
}

function wrapWithGwtComment(spec: TestCaseSpec, body: string): string {
  return [
    `// Given: ${spec.given}`,
    `// When:  ${spec.when}`,
    `// Then:  ${spec.then}`,
    body,
  ].join('\n');
}

interface ParsedBodyOk {
  ok: true;
  imports: string;
  body: string;
}
interface ParsedBodyFail {
  ok: false;
  error: string;
}

/**
 * Robust JSON extractor — handles <think> blocks, markdown fences, and
 * preamble text. Mirrors the parser in `critic-client.ts` and
 * `test-spec-runner.ts`.
 */
export function parseLlmBody(
  rawText: string,
  logger: TrackLogger,
  specId: string,
): ParsedBodyOk | ParsedBodyFail {
  let cleaned = rawText ?? '';
  if (typeof cleaned !== 'string') {
    return { ok: false, error: 'rawText not a string' };
  }
  const hadThink = /<think>[\s\S]*?<\/think>/.test(cleaned);
  cleaned = cleaned.replace(/<think>[\s\S]*?<\/think>/g, '').trim();
  if (hadThink) {
    logBranch(logger, 'agent.emit.spec.parse-decision', {
      decision: 'stripped-think-block',
      specId,
    });
  }
  const hadFence = /^```/.test(cleaned);
  cleaned = cleaned.replace(/^```(?:json)?\s*|\s*```$/g, '').trim();
  if (hadFence) {
    logBranch(logger, 'agent.emit.spec.parse-decision', {
      decision: 'stripped-markdown-fence',
      specId,
    });
  }
  if (!cleaned.startsWith('{')) {
    const m = cleaned.match(/\{[\s\S]*\}/);
    if (m) {
      cleaned = m[0];
      logBranch(logger, 'agent.emit.spec.parse-decision', {
        decision: 'extracted-outer-json',
        specId,
      });
    } else {
      return { ok: false, error: 'no JSON object in response' };
    }
  }

  let parsed: unknown;
  try {
    parsed = JSON.parse(cleaned);
  } catch (e) {
    logCatch(logger, 'agent.emit.spec.parse-decision', e, { specId });
    return { ok: false, error: (e as Error).message };
  }

  const rec = parsed as { imports?: unknown; body?: unknown };
  const imports =
    typeof rec.imports === 'string' ? rec.imports : '';
  const body = typeof rec.body === 'string' ? rec.body : '';
  if (body.trim().length === 0) {
    return { ok: false, error: 'body field empty or missing' };
  }
  return { ok: true, imports, body };
}

// ── Bucketing & file naming ──────────────────────────────────────────────────

function bucketByTarget(specs: TestCaseSpec[]): Map<string, TestCaseSpec[]> {
  const buckets = new Map<string, TestCaseSpec[]>();
  for (const spec of specs) {
    const key = normalizePosix(spec.scope.file || '__unknown__');
    const arr = buckets.get(key);
    if (arr) arr.push(spec);
    else buckets.set(key, [spec]);
  }
  return buckets;
}

function normalizePosix(p: string): string {
  return p.replace(/\\/g, '/');
}

/**
 * Convert e.g. `src/api/login.ts` → `src-api-login`. Strips extension, replaces
 * path separators / unsafe chars with `-`, collapses repeats, lowercases.
 */
export function slugifyTarget(filePath: string): string {
  let s = normalizePosix(filePath);
  // Strip leading ./ or /
  s = s.replace(/^\.?\/+/, '');
  // Strip trailing extension
  s = s.replace(/\.[a-zA-Z0-9]+$/, '');
  s = s.replace(/[^a-zA-Z0-9]+/g, '-');
  s = s.replace(/-+/g, '-');
  s = s.replace(/^-+|-+$/g, '');
  s = s.toLowerCase();
  return s.length > 0 ? s : 'unknown';
}

// ── FunctionInfo matching ────────────────────────────────────────────────────

function indexFunctions(fns: FunctionInfo[]): Map<string, FunctionInfo> {
  const map = new Map<string, FunctionInfo>();
  for (const fn of fns) {
    const file = normalizePosix(fn.file);
    map.set(`${file}#${fn.name}`, fn);
    map.set(`${file}:${fn.line}`, fn);
    // also bare file → first occurrence
    if (!map.has(file)) map.set(file, fn);
  }
  return map;
}

function pickFunctionInfo(
  spec: TestCaseSpec,
  index: Map<string, FunctionInfo>,
): FunctionInfo | null {
  const file = normalizePosix(spec.scope.file);
  // target may look like `fn:hashPassword` or `POST /api/login`
  const targetName = extractTargetName(spec.scope.target);
  if (targetName) {
    const k = `${file}#${targetName}`;
    if (index.has(k)) return index.get(k) ?? null;
  }
  const lineKey = `${file}:${spec.scope.line}`;
  if (index.has(lineKey)) return index.get(lineKey) ?? null;
  return index.get(file) ?? null;
}

function extractTargetName(target: string): string | null {
  // `fn:hashPassword` → hashPassword
  const fnMatch = target.match(/^fn:(.+)$/);
  if (fnMatch && fnMatch[1]) return fnMatch[1].trim();
  // `POST /api/login` → POST (Next-style verb is the export name)
  const verbMatch = target.match(/^(GET|POST|PUT|PATCH|DELETE|HEAD|OPTIONS)\b/);
  if (verbMatch && verbMatch[1]) return verbMatch[1];
  // bare name like `handleLogin`
  if (/^[A-Za-z_$][\w$]*$/.test(target)) return target;
  return null;
}

// ── Prompt build ─────────────────────────────────────────────────────────────

interface BuildPromptArgs {
  spec: TestCaseSpec;
  fnInfo: FunctionInfo | null;
  relImportPath: string;
}

function buildEmitUserPrompt(args: BuildPromptArgs): string {
  const { spec, fnInfo, relImportPath } = args;
  const lines = [
    `Test Specification:`,
    `- ID: ${spec.id}`,
    `- Name: ${spec.name}`,
    `- Category: ${spec.category}`,
    `- Scope type: ${spec.scope.type}`,
    `- Scope target: ${spec.scope.target}`,
    `- Source file: ${spec.scope.file}:${spec.scope.line}`,
    `- Given: ${spec.given}`,
    `- When:  ${spec.when}`,
    `- Then:  ${spec.then}`,
    ``,
    `Suggested relative import path for the source module: ${JSON.stringify(relImportPath)}`,
    ``,
  ];

  if (fnInfo) {
    lines.push(
      `Static analysis of target function:`,
      `- Name: ${fnInfo.name}`,
      `- Kind: ${fnInfo.kind}`,
      `- Has async call: ${fnInfo.hasAsyncCall}`,
      `- Has database call: ${fnInfo.hasDatabaseCall}`,
      `- Has network call: ${fnInfo.hasNetworkCall}`,
      `- Branch count: ${fnInfo.branchCount}`,
      `- Return type hint: ${fnInfo.returnTypeHint ?? '(none)'}`,
      `- Params: ${fnInfo.params
        .map((p) => `${p.name}: ${p.typeHint ?? 'any'}`)
        .join(', ') || '(none)'}`,
      ``,
      `Source snippet (max 200 lines):`,
      '```ts',
      fnInfo.sourceSnippet,
      '```',
      ``,
    );
    if (fnInfo.hasDatabaseCall) {
      lines.push(
        `NOTE: target makes database calls — use vi.mock() to stub the db client.`,
      );
    }
    if (fnInfo.hasNetworkCall) {
      lines.push(
        `NOTE: target makes network calls — use vi.mock() to stub fetch/axios.`,
      );
    }
  } else {
    lines.push(
      `(No static analysis available for this target — author the test from the spec alone.)`,
    );
  }

  lines.push(
    ``,
    `Produce the JSON object now.`,
  );
  return lines.join('\n');
}

// ── File assembly ───────────────────────────────────────────────────────────

interface BuildFileArgs {
  targetFile: string;
  imports: string[];
  rendered: RenderedSpec[];
}

function buildFileContent(args: BuildFileArgs): string {
  const describeName = describeNameFor(args.targetFile, args.rendered);
  const out: string[] = [];

  out.push(`// ZEROU AUTOGENERATED — safe to delete entire tests/__zerou__/ dir`);
  out.push(`// Target source file: ${args.targetFile}`);
  out.push(`// Generated at: ${new Date().toISOString()}`);
  out.push(``);
  out.push(...args.imports);
  out.push(``);
  out.push(`describe(${JSON.stringify(describeName)}, () => {`);
  for (const r of args.rendered) {
    if (r.isTodo) {
      out.push(`  ${r.body}`);
    } else {
      out.push(`  it(${JSON.stringify(r.spec.name)}, async () => {`);
      const indented = r.body
        .split(/\r?\n/)
        .map((l) => (l.length > 0 ? `    ${l}` : l))
        .join('\n');
      out.push(indented);
      out.push(`  });`);
    }
    out.push(``);
  }
  out.push(`});`);
  out.push(``);
  return out.join('\n');
}

function describeNameFor(targetFile: string, rendered: RenderedSpec[]): string {
  // Prefer the first spec's scope.target if it looks meaningful.
  const first = rendered[0];
  if (first && first.spec.scope.target && first.spec.scope.target.length > 0) {
    return first.spec.scope.target;
  }
  return targetFile;
}

// ── Import path math ────────────────────────────────────────────────────────

/**
 * Compute the relative import path from `<outDir>/<slug>.test.ts` back to
 * `<cwd>/<targetFile>`. Returns a POSIX-style path with a leading `./` or
 * `../` and the original extension preserved (vitest can resolve `.ts`
 * directly via tsx/esbuild).
 */
export function computeRelativeImport(
  outDir: string,
  targetFile: string,
  cwd: string,
): string {
  const sourceAbs = path.isAbsolute(targetFile)
    ? targetFile
    : path.resolve(cwd, targetFile);
  let rel = path.relative(outDir, sourceAbs);
  rel = normalizePosix(rel);
  if (!rel.startsWith('.')) rel = './' + rel;
  return rel;
}

// ── Default LLM caller ──────────────────────────────────────────────────────

/**
 * OpenAI-Chat-Completions dialect, same shape as `critic-client.ts`. Returns
 * the assistant's `content` verbatim; `parseLlmBody` handles cleanup.
 */
const defaultEmitLlmCaller: EmitLlmCaller = async ({
  systemPrompt,
  userPrompt,
  criticConfig,
  apiKey,
  timeoutMs,
}) => {
  const baseUrl = criticConfig.baseUrl;
  if (!baseUrl) {
    throw new Error('criticConfig.baseUrl is required for default LLM caller');
  }
  const url = baseUrl.replace(/\/$/, '') + '/chat/completions';
  const start = Date.now();
  const res = await fetch(url, {
    method: 'POST',
    headers: {
      'content-type': 'application/json',
      authorization: `Bearer ${apiKey}`,
    },
    body: JSON.stringify({
      model: criticConfig.modelId,
      messages: [
        { role: 'system', content: systemPrompt },
        { role: 'user', content: userPrompt },
      ],
      temperature: 0,
      stream: false,
    }),
    signal: AbortSignal.timeout(timeoutMs),
  });
  const text = await res.text();
  const durationMs = Date.now() - start;
  if (!res.ok) {
    throw new Error(`HTTP ${res.status}: ${text.slice(0, 200)}`);
  }
  const env = JSON.parse(text) as {
    choices?: Array<{ message?: { content?: string } }>;
  };
  const content = env.choices?.[0]?.message?.content;
  if (typeof content !== 'string' || content.length === 0) {
    throw new Error('response missing choices[0].message.content');
  }
  return { rawText: content, durationMs };
};
