/**
 * Test emitter (Phase 8 Track 8B).
 *
 * Converts `TestCaseSpec[]` (produced by `test-case-generator.ts`) into real
 * Vitest `.test.ts` files written under `<cwd>/tests/__zerou__/`. When a
 * critic LLM is configured the body of each test is generated by the LLM
 * (mock setup + assertions). When no critic is configured we fall back to
 * `it.todo(...)` so vitest still parses the file but treats the case as
 * pending (no false failures, no false passes).
 *
 * Surface authority:
 *   `docs/plans/2026-05-26-phase-8-real-tests-progressive-report.md`
 *   §"agent/test-emitter.ts (Track 8B)".
 *
 * Events emitted (see plan §"Decision-Branch Log Taxonomy"):
 *   agent.emit.start
 *   agent.emit.file.start
 *   agent.emit.spec.llm-call.start
 *   agent.emit.spec.llm-call.success
 *   agent.emit.spec.llm-call.failure
 *   agent.emit.spec.fallback-todo
 *   agent.emit.file.written
 *   agent.emit.complete
 */
import * as fs from 'node:fs';
import path from 'node:path';
import type { TrackLogger } from '../log-types.js';
import { logBranch, logCatch } from '../log/branch.js';
import type { EngineConfig } from '../stubs.js';
import type { TestCaseSpec } from './types.js';
import type { FunctionInfo } from './ast-analyzer.js';
import { fetchLlm } from './llm-fetch.js';
import { runConcurrent } from './concurrency.js';
import type { AuthShape } from './auth-detector.js';
import { fixtureFor, fixtureRelImport, fixtureFileName } from './auth-fixtures.js';

const DEFAULT_CONCURRENCY = 5;

// ── Public surface ──────────────────────────────────────────────────────────

export interface EmittedTestFile {
  /** Absolute path to the written `.test.ts` file. */
  path: string;
  /** Number of `it(...)` / `it.todo(...)` cases in this file. */
  testCount: number;
  /** TestCaseSpec.id values that landed in this file. */
  specsCovered: string[];
  /** Source LOC of the emitted file (newline count). */
  sourceLOC: number;
}

export interface EmitOptions {
  specs: TestCaseSpec[];
  functions: FunctionInfo[];
  cwd: string;
  /** Default `<cwd>/tests/__zerou__`. */
  outDir?: string;
  logger: TrackLogger;
  criticConfig?: EngineConfig | null;
  criticApiKey?: string | null;
  /** Injectable LLM caller — used by tests to avoid hitting a real provider. */
  callLLM?: EmitLlmCaller;
  /** Per-spec LLM call timeout. Default 30s. */
  timeoutMs?: number;
  /**
   * Max concurrent in-flight spec LLM calls per file bucket. Default 5
   * (Phase 11.1). Tests should pass `concurrency: 1` for determinism.
   */
  concurrency?: number;
  /** Optional AbortSignal to short-circuit pending spec renders. */
  signal?: AbortSignal;
  /**
   * Phase 11.3: project auth shape (from `detectAuthShape`). When set,
   * the emitter writes a canonical auth fixture file once and injects
   * `mockAuthenticatedUser` / `mockAnonymous` calls into every emitted
   * test based on its spec.given posture.
   */
  authShape?: AuthShape;
}

/**
 * LLM call hook used to fill in test body + imports. Mirrors the pattern in
 * `test-spec-runner.ts`. The returned `rawText` is expected to contain JSON
 * with `imports` and `body` string fields (see `parseLlmBody` below).
 */
export type EmitLlmCaller = (args: {
  systemPrompt: string;
  userPrompt: string;
  criticConfig: EngineConfig;
  apiKey: string;
  timeoutMs: number;
}) => Promise<{ rawText: string; durationMs: number }>;

/** Public entry point. Writes one `.test.ts` file per source file targeted. */
export async function emitVitestTests(opts: EmitOptions): Promise<EmittedTestFile[]> {
  const start = Date.now();
  const { logger } = opts;
  const outDir = opts.outDir ?? path.join(opts.cwd, 'tests', '__zerou__');
  const timeoutMs = opts.timeoutMs ?? DEFAULT_TIMEOUT_MS;
  const concurrency = opts.concurrency ?? DEFAULT_CONCURRENCY;
  const hasLlm = !!(opts.criticConfig && opts.criticApiKey);

  logger.log('info', 'agent.emit.start', {
    specCount: opts.specs.length,
    functionCount: opts.functions.length,
    outDir,
    hasLlm,
    concurrency,
  });

  // Bucket specs by spec.scope.file → one .test.ts per source file.
  const buckets = bucketByTarget(opts.specs);
  const files: EmittedTestFile[] = [];

  // Ensure the output directory exists (idempotent).
  fs.mkdirSync(outDir, { recursive: true });

  // Phase 11.3: write canonical auth fixture once per audit run (idempotent).
  const authShape = opts.authShape;
  let authFixtureRelImport: string | null = null;
  if (authShape && authShape.kind !== 'none') {
    const tmpl = fixtureFor(authShape.kind);
    if (tmpl) {
      const fixturesDir = path.join(outDir, 'fixtures');
      fs.mkdirSync(fixturesDir, { recursive: true });
      const fixturePath = path.join(fixturesDir, fixtureFileName(authShape.kind));
      try {
        // Idempotent: only write if missing or content differs.
        let existing = '';
        try { existing = fs.readFileSync(fixturePath, 'utf8'); } catch { /* ignore */ }
        if (existing !== tmpl) fs.writeFileSync(fixturePath, tmpl, 'utf8');
        authFixtureRelImport = fixtureRelImport(authShape.kind);
        logger.log('info', 'agent.emit.auth-fixture.written', {
          kind: authShape.kind,
          path: fixturePath,
        });
      } catch (e) {
        logCatch(logger, 'agent.emit.auth-fixture.write-failed', e, {
          kind: authShape.kind,
          path: fixturePath,
        });
      }
    }
  }

  for (const [targetFile, specs] of buckets) {
    logger.log('info', 'agent.emit.file.start', {
      targetFile,
      specCount: specs.length,
    });

    const fnByKey = indexFunctions(opts.functions);
    // Phase 11.3: track imports as structured { source, names, default? } so
    // duplicate `import { vi } from 'vitest'` and `import { vi, expect } from
    // 'vitest'` collapse into ONE consolidated import.
    const importTracker = new ImportTracker();
    importTracker.addParsed(`import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';`);

    // If auth fixture is in play, add the import + ensure beforeEach is in scope.
    if (authFixtureRelImport) {
      importTracker.addParsed(
        `import { mockAuthenticatedUser, mockAnonymous, resetAuth } from '${authFixtureRelImport}';`,
      );
    }

    // Render specs in parallel (bounded by `concurrency`). `renderSpec`
    // never throws — failures collapse to it.todo(...) — so we don't need
    // recovery in this layer.
    const tasks = specs.map((spec) => {
      const fnInfo = pickFunctionInfo(spec, fnByKey);
      return () =>
        renderSpec({
          spec,
          fnInfo,
          targetFile,
          outDir,
          cwd: opts.cwd,
          logger,
          criticConfig: opts.criticConfig ?? null,
          criticApiKey: opts.criticApiKey ?? null,
          callLLM: opts.callLLM,
          timeoutMs,
          authShape,
          authFixtureRelImport,
        });
    });
    const settled = await runConcurrent(tasks, {
      maxInFlight: concurrency,
      logger,
      branchPrefix: 'agent.emit.file',
      signal: opts.signal,
    });
    const rendered: RenderedSpec[] = [];
    for (let i = 0; i < settled.length; i++) {
      const r = settled[i]!;
      if (r.ok && r.value) {
        rendered.push(r.value);
        for (const imp of r.value.imports) importTracker.addParsed(imp);
      } else {
        // Aborted or unexpected — fall back to it.todo so file stays valid.
        const spec = specs[i]!;
        rendered.push({
          spec,
          imports: [],
          body: `it.todo(${JSON.stringify(spec.name)});`,
          isTodo: true,
        });
      }
    }

    const outFilePath = path.join(outDir, `${slugifyTarget(targetFile)}.test.ts`);
    const content = buildFileContent({
      targetFile,
      imports: importTracker.render(),
      rendered,
      authFixtureRelImport,
    });

    try {
      fs.writeFileSync(outFilePath, content, 'utf8');
    } catch (e) {
      logCatch(logger, 'agent.emit.file.write-decision', e, {
        path: outFilePath,
      });
      throw e;
    }

    const sourceLOC = content.split(/\r?\n/).length;
    logger.log('info', 'agent.emit.file.written', {
      path: outFilePath,
      testCount: rendered.length,
      bytes: Buffer.byteLength(content, 'utf8'),
      sourceLOC,
    });

    files.push({
      path: outFilePath,
      testCount: rendered.length,
      specsCovered: rendered.map((r) => r.spec.id),
      sourceLOC,
    });
  }

  logger.log('info', 'agent.emit.complete', {
    fileCount: files.length,
    totalTests: files.reduce((n, f) => n + f.testCount, 0),
    durationMs: Date.now() - start,
  });

  return files;
}

// ── Internals ───────────────────────────────────────────────────────────────

const DEFAULT_TIMEOUT_MS = 30_000;

const SYSTEM_PROMPT = [
  'You are a senior TypeScript test engineer. You write Vitest tests that run in',
  'Node. Given one test specification and the source code under test, output the',
  'body of a single `it(...)` block plus any needed imports.',
  '',
  'OUTPUT FORMAT: strict JSON only, no markdown fence, no preamble. Schema:',
  '{',
  '  "imports": "string — newline-separated extra import statements (may be empty)",',
  '  "body":    "string — the JavaScript/TypeScript inside the it() callback"',
  '}',
  '',
  'Rules:',
  ' - Do NOT include `it(...)`, `describe(...)`, `import { it } from vitest` —',
  '   the harness already provides those.',
  ' - Prefer `await import("<relative path>")` over top-level import for the',
  '   target module so dynamic loading errors do not break collection.',
  ' - Use `vi.mock()` for db / network calls when the source code uses them.',
  ' - Keep the body under 60 lines. If you cannot write a meaningful test,',
  '   return `{"imports": "", "body": "expect.fail(\'TODO: unable to author\');"}`.',
].join('\n');

interface RenderedSpec {
  spec: TestCaseSpec;
  imports: string[];                // extra imports to merge at file top
  body: string;                     // the body of `it(...)`
  isTodo: boolean;                  // true if fell back to it.todo(...)
}

interface RenderSpecArgs {
  spec: TestCaseSpec;
  fnInfo: FunctionInfo | null;
  targetFile: string;               // POSIX-relative source file
  outDir: string;
  cwd: string;
  logger: TrackLogger;
  criticConfig: EngineConfig | null;
  criticApiKey: string | null;
  callLLM?: EmitLlmCaller;
  timeoutMs: number;
  authShape?: AuthShape;
  authFixtureRelImport?: string | null;
}

async function renderSpec(args: RenderSpecArgs): Promise<RenderedSpec> {
  const { spec, fnInfo, targetFile, outDir, cwd, logger } = args;

  if (!args.criticConfig || !args.criticApiKey) {
    logBranch(logger, 'agent.emit.spec.fallback-todo', {
      decision: 'no-llm-key',
      specId: spec.id,
      reason: 'no critic config or api key',
    });
    return {
      spec,
      imports: [],
      body: `it.todo(${JSON.stringify(spec.name)});`,
      isTodo: true,
    };
  }

  const relImportPath = computeRelativeImport(outDir, targetFile, cwd);
  const userPrompt = buildEmitUserPrompt({
    spec,
    fnInfo,
    relImportPath,
    authShape: args.authShape,
    authFixtureRelImport: args.authFixtureRelImport ?? null,
  });

  logger.log('info', 'agent.emit.spec.llm-call.start', {
    specId: spec.id,
    model: args.criticConfig.modelId,
    promptLen: userPrompt.length,
  });

  let rawText = '';
  const callStart = Date.now();
  try {
    const caller = args.callLLM ?? defaultEmitLlmCaller;
    const out = await caller({
      systemPrompt: SYSTEM_PROMPT,
      userPrompt,
      criticConfig: args.criticConfig,
      apiKey: args.criticApiKey,
      timeoutMs: args.timeoutMs,
    });
    rawText = out.rawText;
    logger.log('info', 'agent.emit.spec.llm-call.success', {
      specId: spec.id,
      durationMs: out.durationMs,
      rawLen: rawText.length,
    });
  } catch (e) {
    const msg = e instanceof Error ? e.message : String(e);
    logger.log('warn', 'agent.emit.spec.llm-call.failure', {
      specId: spec.id,
      error: msg.slice(0, 300),
      durationMs: Date.now() - callStart,
    });
    logBranch(logger, 'agent.emit.spec.fallback-todo', {
      decision: 'llm-failure',
      specId: spec.id,
      reason: 'llm call threw',
    });
    return {
      spec,
      imports: [],
      body: `it.todo(${JSON.stringify(spec.name)});`,
      isTodo: true,
    };
  }

  const parsed = parseLlmBody(rawText, logger, spec.id);
  if (!parsed.ok) {
    logBranch(logger, 'agent.emit.spec.fallback-todo', {
      decision: 'parse-failure',
      specId: spec.id,
      reason: parsed.error,
    });
    return {
      spec,
      imports: [],
      body: `it.todo(${JSON.stringify(spec.name)});`,
      isTodo: true,
    };
  }

  const importLines = parsed.imports
    .split(/\r?\n/)
    .map((s) => s.trim())
    .filter((s) => s.length > 0);

  // Phase 11.3: sanitize body — strip any nested `it(`, `describe(`, or
  // top-level test wrappers the LLM may have emitted despite the prompt
  // telling it not to. Without this we get the broken output documented in
  // app-api-me-bets-route.test.ts where a `beforeEach` and a nested `it()`
  // both end up INSIDE another `it()` body.
  const sanitizedBody = sanitizeTestBody(parsed.body, spec.id, logger);

  // Phase 11.3: prepend auth fixture call when authShape + spec.given signals.
  const authPrefix = authPostureForSpec(spec, args.authShape, args.authFixtureRelImport ?? null);
  const finalBody = authPrefix ? `${authPrefix}\n${sanitizedBody}` : sanitizedBody;

  return {
    spec,
    imports: importLines,
    body: wrapWithGwtComment(spec, finalBody),
    isTodo: false,
  };
}

/**
 * Strip top-level `it(...)`, `describe(...)`, or stray `beforeEach(...)` calls
 * from the LLM body. We only want the inside-of-it() content; the harness
 * supplies the outer `it(...)` wrapper itself.
 *
 * Strategy (regex-light, deterministic): walk the body line by line, track
 * brace depth, and elide any line whose top-level (depth=0) statement starts
 * with `it(`, `it.skip(`, `it.only(`, `it.todo(`, `describe(`, `beforeAll(`,
 * `beforeEach(`, `afterAll(`, `afterEach(`. Also elide the closing `})`/`});`
 * that pairs with each elided opener.
 *
 * If, after sanitization, the body is empty, return an `expect.fail(...)`
 * stub so the test still surfaces something to the user.
 */
export function sanitizeTestBody(
  rawBody: string,
  specId: string,
  logger: TrackLogger,
): string {
  const NESTED_OPENERS = /^(?:it|describe|beforeAll|beforeEach|afterAll|afterEach)(?:\.\w+)?\s*\(/;
  const lines = rawBody.split(/\r?\n/);
  const out: string[] = [];
  let topLevelDepth = 0;        // brace depth at the start of each line
  let skipUntilDepth: number | null = null; // when set, drop lines until depth returns to this
  let strippedCount = 0;

  for (const line of lines) {
    const trimmed = line.trim();
    if (skipUntilDepth !== null) {
      // We are inside an elided block — track braces, drop the line.
      topLevelDepth += countCharsOutsideStrings(line, '{') - countCharsOutsideStrings(line, '}');
      topLevelDepth += countCharsOutsideStrings(line, '(') - countCharsOutsideStrings(line, ')');
      if (topLevelDepth <= skipUntilDepth) {
        skipUntilDepth = null;
      }
      strippedCount++;
      continue;
    }
    if (topLevelDepth === 0 && NESTED_OPENERS.test(trimmed)) {
      // Elide this entire block.
      const openersOnLine = countCharsOutsideStrings(line, '(') + countCharsOutsideStrings(line, '{');
      const closersOnLine = countCharsOutsideStrings(line, ')') + countCharsOutsideStrings(line, '}');
      const delta = openersOnLine - closersOnLine;
      strippedCount++;
      if (delta <= 0) {
        // Single-line `it.todo("name");` or similar — already self-closing.
        continue;
      }
      topLevelDepth += delta;
      skipUntilDepth = 0;
      continue;
    }
    topLevelDepth += countCharsOutsideStrings(line, '{') - countCharsOutsideStrings(line, '}');
    topLevelDepth += countCharsOutsideStrings(line, '(') - countCharsOutsideStrings(line, ')');
    out.push(line);
  }

  let cleaned = out.join('\n').replace(/^\s*\n/, '').replace(/\n\s*\n\s*$/, '\n');
  if (strippedCount > 0) {
    logBranch(logger, 'agent.emit.spec.sanitize-decision', {
      decision: 'stripped-nested-test-wrappers',
      specId,
      strippedLines: strippedCount,
    });
  }
  if (cleaned.trim().length === 0) {
    cleaned = `expect.fail('TODO: LLM body collapsed after sanitization');`;
  }
  return cleaned;
}

function countCharsOutsideStrings(line: string, ch: string): number {
  // Heuristic — does not handle template literals / escape sequences fully,
  // but accurate enough for test-body brace counting where we only care
  // about top-level structure.
  let count = 0;
  let inSingle = false;
  let inDouble = false;
  let inBacktick = false;
  for (let i = 0; i < line.length; i++) {
    const c = line[i];
    if (c === '\\') { i++; continue; }
    if (!inDouble && !inBacktick && c === "'") inSingle = !inSingle;
    else if (!inSingle && !inBacktick && c === '"') inDouble = !inDouble;
    else if (!inSingle && !inDouble && c === '`') inBacktick = !inBacktick;
    else if (!inSingle && !inDouble && !inBacktick && c === ch) count++;
  }
  return count;
}

/**
 * Pick the right auth posture for this spec by inspecting `spec.given`.
 * Returns a code snippet to inject before the spec body (inside the it()),
 * or null if no auth fixture is in play.
 *
 *   given mentions 'anonymous' / 'unauthenticated' / 'no session' → mockAnonymous()
 *   given mentions 'authenticated' / 'logged in' / 'user a' (default for IDOR) → mockAuthenticatedUser()
 *   otherwise: default to authenticated (most specs assume reaching business logic).
 */
function authPostureForSpec(
  spec: TestCaseSpec,
  authShape: AuthShape | undefined,
  fixtureRelImportPath: string | null,
): string | null {
  if (!authShape || authShape.kind === 'none' || !fixtureRelImportPath) return null;
  const given = (spec.given ?? '').toLowerCase();
  if (/anonymous|unauthenticated|no session|without (?:a |the )?session|no auth/.test(given)) {
    return `mockAnonymous();`;
  }
  if (/authenticated|logged in|valid session|signed-in|signed in/.test(given)) {
    return `mockAuthenticatedUser();`;
  }
  // Default: most specs in real audits assume reaching business logic, so
  // they need an authenticated user. The category is the tiebreaker — auth
  // category specs default to anonymous (testing the gate), others to authed.
  if (spec.category === 'auth' || spec.category === 'security') {
    if (/missing auth|bypass|cookie tampering|forge/.test(given)) {
      return `mockAnonymous();`;
    }
  }
  return `mockAuthenticatedUser();`;
}

function wrapWithGwtComment(spec: TestCaseSpec, body: string): string {
  return [
    `// Given: ${spec.given}`,
    `// When:  ${spec.when}`,
    `// Then:  ${spec.then}`,
    body,
  ].join('\n');
}

interface ParsedBodyOk {
  ok: true;
  imports: string;
  body: string;
}
interface ParsedBodyFail {
  ok: false;
  error: string;
}

/**
 * Robust JSON extractor — handles <think> blocks, markdown fences, and
 * preamble text. Mirrors the parser in `critic-client.ts` and
 * `test-spec-runner.ts`.
 */
export function parseLlmBody(
  rawText: string,
  logger: TrackLogger,
  specId: string,
): ParsedBodyOk | ParsedBodyFail {
  let cleaned = rawText ?? '';
  if (typeof cleaned !== 'string') {
    return { ok: false, error: 'rawText not a string' };
  }
  const hadThink = /<think>[\s\S]*?<\/think>/.test(cleaned);
  cleaned = cleaned.replace(/<think>[\s\S]*?<\/think>/g, '').trim();
  if (hadThink) {
    logBranch(logger, 'agent.emit.spec.parse-decision', {
      decision: 'stripped-think-block',
      specId,
    });
  }
  const hadFence = /^```/.test(cleaned);
  cleaned = cleaned.replace(/^```(?:json)?\s*|\s*```$/g, '').trim();
  if (hadFence) {
    logBranch(logger, 'agent.emit.spec.parse-decision', {
      decision: 'stripped-markdown-fence',
      specId,
    });
  }
  if (!cleaned.startsWith('{')) {
    const m = cleaned.match(/\{[\s\S]*\}/);
    if (m) {
      cleaned = m[0];
      logBranch(logger, 'agent.emit.spec.parse-decision', {
        decision: 'extracted-outer-json',
        specId,
      });
    } else {
      return { ok: false, error: 'no JSON object in response' };
    }
  }

  let parsed: unknown;
  try {
    parsed = JSON.parse(cleaned);
  } catch (e) {
    logCatch(logger, 'agent.emit.spec.parse-decision', e, { specId });
    return { ok: false, error: (e as Error).message };
  }

  const rec = parsed as { imports?: unknown; body?: unknown };
  const imports =
    typeof rec.imports === 'string' ? rec.imports : '';
  const body = typeof rec.body === 'string' ? rec.body : '';
  if (body.trim().length === 0) {
    return { ok: false, error: 'body field empty or missing' };
  }
  return { ok: true, imports, body };
}

// ── Bucketing & file naming ──────────────────────────────────────────────────

function bucketByTarget(specs: TestCaseSpec[]): Map<string, TestCaseSpec[]> {
  const buckets = new Map<string, TestCaseSpec[]>();
  for (const spec of specs) {
    const key = normalizePosix(spec.scope.file || '__unknown__');
    const arr = buckets.get(key);
    if (arr) arr.push(spec);
    else buckets.set(key, [spec]);
  }
  return buckets;
}

function normalizePosix(p: string): string {
  return p.replace(/\\/g, '/');
}

/**
 * Convert e.g. `src/api/login.ts` → `src-api-login`. Strips extension, replaces
 * path separators / unsafe chars with `-`, collapses repeats, lowercases.
 */
export function slugifyTarget(filePath: string): string {
  let s = normalizePosix(filePath);
  // Strip leading ./ or /
  s = s.replace(/^\.?\/+/, '');
  // Strip trailing extension
  s = s.replace(/\.[a-zA-Z0-9]+$/, '');
  s = s.replace(/[^a-zA-Z0-9]+/g, '-');
  s = s.replace(/-+/g, '-');
  s = s.replace(/^-+|-+$/g, '');
  s = s.toLowerCase();
  return s.length > 0 ? s : 'unknown';
}

// ── FunctionInfo matching ────────────────────────────────────────────────────

function indexFunctions(fns: FunctionInfo[]): Map<string, FunctionInfo> {
  const map = new Map<string, FunctionInfo>();
  for (const fn of fns) {
    const file = normalizePosix(fn.file);
    map.set(`${file}#${fn.name}`, fn);
    map.set(`${file}:${fn.line}`, fn);
    // also bare file → first occurrence
    if (!map.has(file)) map.set(file, fn);
  }
  return map;
}

function pickFunctionInfo(
  spec: TestCaseSpec,
  index: Map<string, FunctionInfo>,
): FunctionInfo | null {
  const file = normalizePosix(spec.scope.file);
  // target may look like `fn:hashPassword` or `POST /api/login`
  const targetName = extractTargetName(spec.scope.target);
  if (targetName) {
    const k = `${file}#${targetName}`;
    if (index.has(k)) return index.get(k) ?? null;
  }
  const lineKey = `${file}:${spec.scope.line}`;
  if (index.has(lineKey)) return index.get(lineKey) ?? null;
  return index.get(file) ?? null;
}

function extractTargetName(target: string): string | null {
  // `fn:hashPassword` → hashPassword
  const fnMatch = target.match(/^fn:(.+)$/);
  if (fnMatch && fnMatch[1]) return fnMatch[1].trim();
  // `POST /api/login` → POST (Next-style verb is the export name)
  const verbMatch = target.match(/^(GET|POST|PUT|PATCH|DELETE|HEAD|OPTIONS)\b/);
  if (verbMatch && verbMatch[1]) return verbMatch[1];
  // bare name like `handleLogin`
  if (/^[A-Za-z_$][\w$]*$/.test(target)) return target;
  return null;
}

// ── Prompt build ─────────────────────────────────────────────────────────────

interface BuildPromptArgs {
  spec: TestCaseSpec;
  fnInfo: FunctionInfo | null;
  relImportPath: string;
  authShape?: AuthShape;
  authFixtureRelImport?: string | null;
}

function buildEmitUserPrompt(args: BuildPromptArgs): string {
  const { spec, fnInfo, relImportPath, authShape, authFixtureRelImport } = args;
  const lines = [
    `Test Specification:`,
    `- ID: ${spec.id}`,
    `- Name: ${spec.name}`,
    `- Category: ${spec.category}`,
    `- Scope type: ${spec.scope.type}`,
    `- Scope target: ${spec.scope.target}`,
    `- Source file: ${spec.scope.file}:${spec.scope.line}`,
    `- Given: ${spec.given}`,
    `- When:  ${spec.when}`,
    `- Then:  ${spec.then}`,
    ``,
    `Suggested relative import path for the source module: ${JSON.stringify(relImportPath)}`,
    ``,
  ];

  if (fnInfo) {
    lines.push(
      `Static analysis of target function:`,
      `- Name: ${fnInfo.name}`,
      `- Kind: ${fnInfo.kind}`,
      `- Has async call: ${fnInfo.hasAsyncCall}`,
      `- Has database call: ${fnInfo.hasDatabaseCall}`,
      `- Has network call: ${fnInfo.hasNetworkCall}`,
      `- Branch count: ${fnInfo.branchCount}`,
      `- Return type hint: ${fnInfo.returnTypeHint ?? '(none)'}`,
      `- Params: ${fnInfo.params
        .map((p) => `${p.name}: ${p.typeHint ?? 'any'}`)
        .join(', ') || '(none)'}`,
      ``,
      `Source snippet (max 200 lines):`,
      '```ts',
      fnInfo.sourceSnippet,
      '```',
      ``,
    );
    if (fnInfo.hasDatabaseCall) {
      lines.push(
        `NOTE: target makes database calls — use vi.mock() to stub the db client.`,
      );
    }
    if (fnInfo.hasNetworkCall) {
      lines.push(
        `NOTE: target makes network calls — use vi.mock() to stub fetch/axios.`,
      );
    }
  } else {
    lines.push(
      `(No static analysis available for this target — author the test from the spec alone.)`,
    );
  }

  if (authShape && authShape.kind !== 'none' && authFixtureRelImport) {
    lines.push(
      ``,
      `Authentication context: this project uses ${authShape.kind}.`,
      `Auth helper: ${authShape.helperFunctionName ?? 'unknown'} from ${authShape.helperImport ?? '(relative)'}.`,
      `A canonical fixture is available at ${authFixtureRelImport} — exports:`,
      `  - mockAuthenticatedUser(user?)  → mocks the auth helper to return a user`,
      `  - mockAnonymous()                → mocks the auth helper to return null`,
      `  - resetAuth()                    → reset between tests`,
      `The harness has ALREADY imported these and (based on spec.given) will`,
      `call mockAuthenticatedUser() or mockAnonymous() before your body runs.`,
      `DO NOT emit your own vi.mock() of the auth helper — it's already done`,
      `at fixture load time and would conflict.`,
    );
  }
  lines.push(
    ``,
    `IMPORTANT: output ONLY the body of a single it() block. Do NOT include`,
    `\`it(...)\`, \`describe(...)\`, \`beforeEach(...)\`, or other test wrappers`,
    `in the body field — they will be stripped or break the file.`,
    ``,
    `Produce the JSON object now.`,
  );
  return lines.join('\n');
}

// ── File assembly ───────────────────────────────────────────────────────────

interface BuildFileArgs {
  targetFile: string;
  imports: string[];
  rendered: RenderedSpec[];
  authFixtureRelImport?: string | null;
}

function buildFileContent(args: BuildFileArgs): string {
  const describeName = describeNameFor(args.targetFile, args.rendered);
  const out: string[] = [];

  out.push(`// ZEROU AUTOGENERATED — safe to delete entire tests/__zerou__/ dir`);
  out.push(`// Target source file: ${args.targetFile}`);
  out.push(`// Generated at: ${new Date().toISOString()}`);
  out.push(``);
  out.push(...args.imports);
  out.push(``);
  out.push(`describe(${JSON.stringify(describeName)}, () => {`);
  if (args.authFixtureRelImport) {
    out.push(`  afterEach(() => { resetAuth(); });`);
    out.push(``);
  }
  for (const r of args.rendered) {
    if (r.isTodo) {
      out.push(`  ${r.body}`);
    } else {
      out.push(`  it(${JSON.stringify(r.spec.name)}, async () => {`);
      const indented = r.body
        .split(/\r?\n/)
        .map((l) => (l.length > 0 ? `    ${l}` : l))
        .join('\n');
      out.push(indented);
      out.push(`  });`);
    }
    out.push(``);
  }
  out.push(`});`);
  out.push(``);
  return out.join('\n');
}

// ── Import deduplication ────────────────────────────────────────────────────

/**
 * Parses + merges `import` statements so the file ends up with one
 * consolidated line per `from '...'` source.
 *
 * Handles three forms:
 *   import X from 'mod';                  (default)
 *   import { a, b } from 'mod';           (named)
 *   import * as ns from 'mod';            (namespace)
 *   side-effect imports like `import 'foo'` are kept as-is (rare).
 *
 * Output ordering: the tracker preserves the FIRST seen `from` source order
 * so deterministic output is predictable.
 */
interface ParsedImport {
  source: string;
  names: Set<string>;       // named imports
  default: string | null;   // default import binding
  namespace: string | null; // `* as ns` binding
  /** Raw line for non-parseable statements (e.g. side-effect imports). */
  raw?: string;
}

export class ImportTracker {
  private bySource = new Map<string, ParsedImport>();
  private order: string[] = [];
  private rawSideEffects: string[] = [];

  /** Add a (possibly multi-line) import statement. Robust to malformed input. */
  addParsed(line: string): void {
    const trimmed = line.trim().replace(/;$/, '').trim();
    if (!trimmed.startsWith('import')) {
      // Not actually an import — keep as opaque line. Avoid swallowing user code.
      if (!this.rawSideEffects.includes(line.trim())) {
        this.rawSideEffects.push(line.trim());
      }
      return;
    }

    // Side-effect: `import 'foo';`
    const sideEffectRe = /^import\s+(['"])([^'"]+)\1$/;
    const seM = sideEffectRe.exec(trimmed);
    if (seM) {
      const src = seM[2]!;
      this.touchSource(src).raw = `import ${JSON.stringify(src)};`;
      return;
    }

    // Forms: `import X from 'mod'`, `import { a, b } from 'mod'`,
    //        `import X, { a, b } from 'mod'`, `import * as ns from 'mod'`,
    //        `import X, * as ns from 'mod'`
    const fromRe = /^import\s+([\s\S]+?)\s+from\s+(['"])([^'"]+)\2$/;
    const m = fromRe.exec(trimmed);
    if (!m) {
      // Unparseable — keep verbatim to be safe.
      if (!this.rawSideEffects.includes(trimmed + ';')) {
        this.rawSideEffects.push(trimmed + ';');
      }
      return;
    }
    const clausePart = m[1]!.trim();
    const source = m[3]!;
    const entry = this.touchSource(source);

    // Walk the clause(s).
    const clauses = splitTopLevel(clausePart, ',');
    for (const c of clauses.map((s) => s.trim()).filter(Boolean)) {
      if (c.startsWith('{') && c.endsWith('}')) {
        // Named imports: `{a, b as B}` — strip braces, split.
        const body = c.slice(1, -1);
        const names = body.split(',').map((s) => s.trim()).filter(Boolean);
        for (const n of names) entry.names.add(normalizeNamedImport(n));
      } else if (c.startsWith('*')) {
        // `* as ns`
        const nsM = /^\*\s*as\s+([A-Za-z_$][\w$]*)$/.exec(c);
        if (nsM) entry.namespace = nsM[1]!;
      } else if (/^[A-Za-z_$][\w$]*$/.test(c)) {
        entry.default = c;
      }
    }
  }

  private touchSource(source: string): ParsedImport {
    let e = this.bySource.get(source);
    if (!e) {
      e = { source, names: new Set(), default: null, namespace: null };
      this.bySource.set(source, e);
      this.order.push(source);
    }
    return e;
  }

  render(): string[] {
    const out: string[] = [];
    for (const src of this.order) {
      const e = this.bySource.get(src)!;
      if (e.raw) {
        out.push(e.raw);
        continue;
      }
      const pieces: string[] = [];
      if (e.default) pieces.push(e.default);
      if (e.namespace) pieces.push(`* as ${e.namespace}`);
      if (e.names.size > 0) {
        const sorted = [...e.names].sort((a, b) => a.localeCompare(b));
        pieces.push(`{ ${sorted.join(', ')} }`);
      }
      if (pieces.length === 0) {
        out.push(`import ${JSON.stringify(src)};`);
      } else {
        out.push(`import ${pieces.join(', ')} from ${JSON.stringify(src)};`);
      }
    }
    out.push(...this.rawSideEffects);
    return out;
  }
}

function normalizeNamedImport(s: string): string {
  // `a as B` — keep entire alias for correctness.
  return s.replace(/\s+/g, ' ').trim();
}

function splitTopLevel(s: string, sep: string): string[] {
  // Splits a clause-list on `sep` ignoring sep inside `{ ... }` groups.
  const out: string[] = [];
  let depth = 0;
  let buf = '';
  for (const c of s) {
    if (c === '{') depth++;
    else if (c === '}') depth--;
    if (c === sep && depth === 0) {
      out.push(buf);
      buf = '';
    } else {
      buf += c;
    }
  }
  if (buf) out.push(buf);
  return out;
}

function describeNameFor(targetFile: string, rendered: RenderedSpec[]): string {
  // Prefer the first spec's scope.target if it looks meaningful.
  const first = rendered[0];
  if (first && first.spec.scope.target && first.spec.scope.target.length > 0) {
    return first.spec.scope.target;
  }
  return targetFile;
}

// ── Import path math ────────────────────────────────────────────────────────

/**
 * Compute the relative import path from `<outDir>/<slug>.test.ts` back to
 * `<cwd>/<targetFile>`. Returns a POSIX-style path with a leading `./` or
 * `../` and the original extension preserved (vitest can resolve `.ts`
 * directly via tsx/esbuild).
 */
export function computeRelativeImport(
  outDir: string,
  targetFile: string,
  cwd: string,
): string {
  const sourceAbs = path.isAbsolute(targetFile)
    ? targetFile
    : path.resolve(cwd, targetFile);
  let rel = path.relative(outDir, sourceAbs);
  rel = normalizePosix(rel);
  if (!rel.startsWith('.')) rel = './' + rel;
  return rel;
}

// ── Default LLM caller ──────────────────────────────────────────────────────

/**
 * OpenAI-Chat-Completions dialect, same shape as `critic-client.ts`. Returns
 * the assistant's `content` verbatim; `parseLlmBody` handles cleanup.
 */
const defaultEmitLlmCaller: EmitLlmCaller = async ({
  systemPrompt,
  userPrompt,
  criticConfig,
  apiKey,
  timeoutMs,
}) => {
  const baseUrl = criticConfig.baseUrl;
  if (!baseUrl) {
    throw new Error('criticConfig.baseUrl is required for default LLM caller');
  }
  const url = baseUrl.replace(/\/$/, '') + '/chat/completions';
  const out = await fetchLlm({
    url,
    apiKey,
    model: criticConfig.modelId,
    systemPrompt,
    userPrompt,
    timeoutMs,
    branchPrefix: 'agent.emit.llm-fetch',
  });
  if (!out.ok) {
    throw new Error(out.error);
  }
  return { rawText: out.rawText, durationMs: out.durationMs };
};
